### ISSUE TITLE
Include sections that were not answered in the form

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/stopadforms#48]
> If a section is left blank, we would like to see that this is the case (i.e. melting point, etc.)

IIRC, if a section is left blank it is not included in the data saved by the form. However, we do know the list of all possible sections, so perhaps we can add it back in.

**Comment by Aryllen** [comment]
> > If a section is left blank, we would like to see that this is the case (i.e. melting point, etc.)

"melting point" isn't a section itself, but rather one of the variables/labels within a section. It is correct that the form does not have missing sections (we could add them in), but if I remember correctly, the form does have the missing variables. I have been removing these to keep the form tidy. So do they want the actual missing section or the missing variables within a section?

**Comment by karawoo** [comment]
Good question, I'm not sure, I will ask

**Comment by karawoo** [comment]
Discussed with Paul yesterday, they want both fields and whole sections that were not provided.
