### ISSUE TITLE
Accept/reject submissions

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/stopadforms#7]
At the very least, it would be handy to have a function to accept/reject submissions for maintaining the S3 bucket. This could then be added as a functionality for the users of the app, as well.

One potential issue is if the user (or maintainer) accepts/rejects a submission accidentally or decides later that they want to change the response. There should also be a way to see submissions with accept or reject statuses and reset the status, perhaps back to "SUBMITTED_WAITING_FOR_REVIEW".

**Comment by Aryllen** [comment]
This one is on hold for the moment until it's verified that we are adding this feature.

**Comment by karawoo** [comment]
I'm removing the blocked label as there's nothing preventing us from doing it, but we still need to decide if we actually will.

**Comment by JessterB** [comment]
I don't see a way to accept or reject in the app. How do submissions get accepted or rejected currently?

**Comment by JessterB** [comment]
Ported this issue to JIRA: https://sagebionetworks.jira.com/browse/ALZ-92
