### ISSUE TITLE
Populate score and comments

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/stopadforms#79]
From Paul: 

> 3) On the “Review & Score” tab, the team wondered if we can have the values for the various score section populate the controls when we select the dropdown. That is to say, if the reviewer has submitted something for the section, can we populate the values so they can review these? The rational is that several team members couldn’t tell what they scored the section, since the controls blank themselves on submission, and as such they were not sure if they needed to rescore this or not.
>
> 4) On the “Review & Score” tab, the team wondered if the comment textbox could also be repopulated upon section of the category. Similar to the values of the controls above, they would like to see if they have entered a comment or not for this portion, but upon submitting this blanks the control.

**Comment by JessterB** [comment]
Ported to JIRA: https://sagebionetworks.jira.com/browse/ALZ-93
