### ISSUE TITLE
Order of sections in "View summarized scores" tab

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/stopadforms#80]
> 5) On the “View summarized scores” tab, would it be possible to list all of the section in the same order as the “select section” dropdown on the “Review & Score” tab? Currently we have things slightly out of order and this makes it hard to review with the team when we discuss these (see below). For instance, the Efficacy is split into two areas, and the order seems to be different than in the above described dropdown.

![image002](https://user-images.githubusercontent.com/4452678/101537949-35a3e600-3951-11eb-8636-9e773c698b30.png)

**Comment by JessterB** [comment]
Ported to JIRA: https://sagebionetworks.jira.com/browse/ALZ-94
